trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**/README.md'

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: liam-goodchild/pipeline-engineering-templates
      endpoint: liam-goodchild
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Prod
  - name: additionalTfVars
    displayName: Additional Terraform Variables
    type: string
    default: ' '
  - name: enableVersioning
    displayName: Enable Git Versioning
    type: boolean
    default: true

variables:
  # Container, Service Connection & tfvars
  backendContainerName: infra-template-base
  serviceConnectionName: sh-sc-base
  globalTfvars: infra/vars/globals.tfvars
  tfvars: infra/vars/uks/$(environmentCode).tfvars
  # State Management
  ${{ if eq(parameters.environment, 'Prod') }}:
    backendResourceGroupName: sh-mgmt-prd-uks-tf-rg-01
    backendStorageAccountName: shmgmtprdukstfst01
    environmentCode: prd
  ${{ else }}:
    backendResourceGroupName: sh-mgmt-dev-uks-tf-rg-01
    backendStorageAccountName: shmgmtdevukstfst01
    environmentCode: dev

stages:
  # Stage 1: Terraform Plan
  - stage: Plan
    displayName: 'Terraform Plan'
    jobs:
      - job: TerraformPlan
        displayName: 'Terraform Plan'
        steps:
          - checkout: self
          - template: terraform/terraform-cicd.yaml@templates
            parameters:
              terraformAction: plan
              serviceConnectionName: $(serviceConnectionName)
              backendResourceGroupName: $(backendResourceGroupName)
              backendStorageAccountName: $(backendStorageAccountName)
              backendContainerName: $(backendContainerName)
              backendKey: terraform.tfstate
              envTfvars: $(tfvars)
              globalTfvars: $(globalTfvars)
              additionalCommandOptions: ${{ parameters.additionalTfVars }}
              publishPlan: true
              planArtifactName: 'tfplan-${{ parameters.environment }}'
              ensureBackendContainer: true

  # Stage 2: Terraform Apply
  - stage: Apply
    displayName: 'Terraform Apply'
    dependsOn: Plan
    condition: succeeded()
    jobs:
      - job: TerraformApply
        displayName: 'Terraform Apply'
        steps:
          - checkout: self
          - template: terraform/terraform-cicd.yaml@templates
            parameters:
              terraformAction: apply
              serviceConnectionName: $(serviceConnectionName)
              backendResourceGroupName: $(backendResourceGroupName)
              backendStorageAccountName: $(backendStorageAccountName)
              backendContainerName: $(backendContainerName)
              backendKey: terraform.tfstate
              envTfvars: $(tfvars)
              globalTfvars: $(globalTfvars)
              additionalCommandOptions: ${{ parameters.additionalTfVars }}
              ensureBackendContainer: false

  # Stage 3: Git Versioning
  - stage: Versioning
    displayName: 'Git Versioning'
    dependsOn: Apply
    condition: and(succeeded(), eq('${{ parameters.enableVersioning }}', 'true'))
    jobs:
      - job: GitVersioning
        displayName: 'Create Git Tag'
        steps:
          - template: versioning/git-versioning.yaml@templates
            parameters:
              defaultAction: patch
              defaultBranch: main
