trigger: none

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**/README.md'

resources:
  repositories:
    - repository: templates
      type: github
      name: liam-goodchild/pipeline-engineering-templates
      endpoint: liam-goodchild
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Prod
  - name: additionalTfVars
    displayName: Additional Terraform Variables
    type: string
    default: ' '

variables:
  # Container, Service Connection & tfvars
  backendContainerName: infra-template-base
  serviceConnectionName: sh-sc-base
  globalTfvars: infra/vars/globals.tfvars
  tfvars: infra/vars/uks/$(environmentCode).tfvars
  # State Management
  ${{ if eq(parameters.environment, 'Prod') }}:
    backendResourceGroupName: sh-mgmt-prd-uks-tf-rg-01
    backendStorageAccountName: shmgmtprdukstfst01
    environmentCode: prd
  ${{ else }}:
    backendResourceGroupName: sh-mgmt-dev-uks-tf-rg-01
    backendStorageAccountName: shmgmtdevukstfst01
    environmentCode: dev

stages:
  # Stage 1: Linting
  - stage: Linting
    displayName: 'Linting & Validation'
    jobs:
      - job: SuperLinter
        displayName: 'Super-Linter'
        steps:
          - template: validation/linting.yaml@templates
            parameters:
              prettierConfigFile: .azuredevops/linters/.prettierrc.json
              checkovConfigFile: .azuredevops/linters/.checkov.yaml

  # Stage 2: Documentation
  - stage: Documentation
    displayName: 'Terraform Documentation'
    dependsOn: Linting
    condition: succeeded()
    jobs:
      - job: TerraformDocs
        displayName: 'Generate Terraform Docs'
        steps:
          - template: documentation/tf-documentation.yaml@templates
            parameters:
              terraformDir: infra
              targetBranch: $(System.PullRequest.SourceBranch)

  # Stage 3: Terraform Plan
  - stage: Plan
    displayName: 'Terraform Plan'
    dependsOn: Documentation
    condition: succeeded()
    jobs:
      - job: TerraformPlan
        displayName: 'Terraform Plan'
        steps:
          - checkout: self
          - template: terraform/terraform-cicd.yaml@templates
            parameters:
              terraformAction: plan
              serviceConnectionName: $(serviceConnectionName)
              backendResourceGroupName: $(backendResourceGroupName)
              backendStorageAccountName: $(backendStorageAccountName)
              backendContainerName: $(backendContainerName)
              backendKey: terraform.tfstate
              envTfvars: $(tfvars)
              globalTfvars: $(globalTfvars)
              additionalCommandOptions: ${{ parameters.additionalTfVars }}
              publishPlan: false
              ensureBackendContainer: true
