trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: liam-goodchild/pipeline-engineering-templates
      endpoint: liam-goodchild
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Prod
  - name: confirmDestroy
    displayName: 'Type "DESTROY" to confirm'
    type: string
    default: ''
  - name: additionalTfVars
    displayName: Additional Terraform Variables
    type: string
    default: ' '

variables:
  # Container, Service Connection & tfvars
  backendContainerName: infra-template-base
  serviceConnectionName: sh-sc-base
  globalTfvars: infra/vars/globals.tfvars
  tfvars: infra/vars/uks/$(environmentCode).tfvars
  # State Management
  ${{ if eq(parameters.environment, 'Prod') }}:
    backendResourceGroupName: sh-mgmt-prd-uks-tf-rg-01
    backendStorageAccountName: shmgmtprdukstfst01
    environmentCode: prd
  ${{ else }}:
    backendResourceGroupName: sh-mgmt-dev-uks-tf-rg-01
    backendStorageAccountName: shmgmtdevukstfst01
    environmentCode: dev

stages:
  - stage: Validation
    displayName: 'Validate Destroy Request'
    jobs:
      - job: ValidateConfirmation
        displayName: 'Validate Confirmation'
        steps:
          - pwsh: |
              if ("${{ parameters.confirmDestroy }}" -ne "DESTROY") {
                Write-Host "##[error]Destroy confirmation failed. You must type 'DESTROY' to confirm."
                Write-Host "##[error]This is a safety measure to prevent accidental destruction of resources."
                exit 1
              }
              Write-Host "##[section]Destroy confirmation validated."
            displayName: 'Check Confirmation'

  - stage: Destroy
    displayName: 'Terraform Destroy'
    dependsOn: Validation
    condition: succeeded()
    jobs:
      - job: TerraformDestroy
        displayName: 'Terraform Destroy - ${{ parameters.environment }}'
        steps:
          - checkout: self
          - template: terraform/terraform-cicd.yaml@templates
            parameters:
              terraformAction: destroy
              serviceConnectionName: $(serviceConnectionName)
              backendResourceGroupName: $(backendResourceGroupName)
              backendStorageAccountName: $(backendStorageAccountName)
              backendContainerName: $(backendContainerName)
              backendKey: terraform.tfstate
              envTfvars: $(tfvars)
              globalTfvars: $(globalTfvars)
              additionalCommandOptions: ${{ parameters.additionalTfVars }}
              ensureBackendContainer: false
