trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: liam-goodchild/pipeline-engineering-templates
      endpoint: liam-goodchild
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: prd
  - name: confirmDestroy
    displayName: 'Type "DESTROY" to confirm'
    type: string
    default: ''
  - name: additionalTfVars
    displayName: Additional Terraform Variables
    type: string
    default: ' '
  - name: envs
    type: object
    default:
      dev:
        backendResourceGroupName: sh-mgmt-dev-uks-tf-rg-01
        backendStorageAccountName: shmgmtdevukstfst01
        tfvars: infra/vars/uks/dev.tfvars
      prd:
        backendResourceGroupName: sh-mgmt-prd-uks-tf-rg-01
        backendStorageAccountName: shmgmtprdukstfst01
        tfvars: infra/vars/uks/prd.tfvars

variables:
  backendContainerName: solution-powertoggle-core
  serviceConnectionName: sh-sc-powertoggle
  globalTfvars: infra/vars/globals.tfvars
  backendResourceGroupName: ${{ parameters.envs[parameters.environment].backendResourceGroupName }}
  backendStorageAccountName: ${{ parameters.envs[parameters.environment].backendStorageAccountName }}
  tfvars: ${{ parameters.envs[parameters.environment].tfvars }}

stages:
  - stage: Validation
    displayName: 'Validate Destroy Request'
    jobs:
      - job: ValidateConfirmation
        displayName: 'Validate Confirmation'
        steps:
          - pwsh: |
              if ("${{ parameters.confirmDestroy }}" -ne "DESTROY") {
                Write-Host "##[error]Destroy confirmation failed. You must type 'DESTROY' to confirm."
                Write-Host "##[error]This is a safety measure to prevent accidental destruction of resources."
                exit 1
              }
              Write-Host "##[section]Destroy confirmation validated."
            displayName: 'Check Confirmation'

  - stage: Destroy
    displayName: 'Terraform Destroy'
    dependsOn: Validation
    condition: succeeded()
    jobs:
      - job: TerraformDestroy
        displayName: 'Terraform Destroy - ${{ parameters.environment }}'
        steps:
          - checkout: self
          - template: terraform/terraform-cicd.yaml@templates
            parameters:
              terraformAction: destroy
              serviceConnectionName: $(serviceConnectionName)
              backendResourceGroupName: $(backendResourceGroupName)
              backendStorageAccountName: $(backendStorageAccountName)
              backendContainerName: $(backendContainerName)
              backendKey: terraform.tfstate
              envTfvars: $(tfvars)
              globalTfvars: $(globalTfvars)
              additionalCommandOptions: '${{ parameters.additionalTfVars }} -var=enable_eventgrid_subscription=true'
              ensureBackendContainer: false
