trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: liam-goodchild/pipeline-engineering-templates
      endpoint: liam-goodchild
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: terraformAction
    displayName: Terraform Action
    type: string
    default: Plan
    values: [Plan, Apply, Destroy]
  - name: environment
    displayName: Environment
    type: string
    default: dev
    values: [dev, prd]
  - name: enableEventGrid
    displayName: Enable Event Grid Subscription
    type: boolean
    default: false
  - name: additionalTfVars
    displayName: Additional Terraform Variables
    type: string
    default: ' '
  - name: envs
    type: object
    default:
      dev:
        backendResourceGroupName: sh-mgmt-dev-uks-tf-rg-01
        backendStorageAccountName: shmgmtdevukstfst01
        tfvars: infra/vars/uks/dev.tfvars
        functionAppName: sh-app-dev-uks-pwt-fa-01
        functionResourceGroupName: sh-app-dev-uks-pwt-rg-01
        eventgridFunctionName: TagIngest
      prd:
        backendResourceGroupName: sh-mgmt-prd-uks-tf-rg-01
        backendStorageAccountName: shmgmtprdukstfst01
        tfvars: infra/vars/uks/prd.tfvars
        functionAppName: sh-app-prd-uks-pwt-fa-01
        functionResourceGroupName: sh-app-prd-uks-pwt-rg-01
        eventgridFunctionName: TagIngest

variables:
  backendContainerName: solution-powertoggle-core
  serviceConnectionName: sh-sc-powertoggle
  globalTfvars: infra/vars/globals.tfvars
  backendResourceGroupName: ${{ parameters.envs[parameters.environment].backendResourceGroupName }}
  backendStorageAccountName: ${{ parameters.envs[parameters.environment].backendStorageAccountName }}
  tfvars: ${{ parameters.envs[parameters.environment].tfvars }}
  functionAppName: ${{ parameters.envs[parameters.environment].functionAppName }}
  functionResourceGroupName: ${{ parameters.envs[parameters.environment].functionResourceGroupName }}
  eventgridFunctionName: ${{ parameters.envs[parameters.environment].eventgridFunctionName }}
  ${{ if eq(parameters.enableEventGrid, true) }}:
    eventGridArg: '-var=enable_eventgrid_subscription=true'
  ${{ else }}:
    eventGridArg: '-var=enable_eventgrid_subscription=false'

stages:
  # Terraform Plan
  - ${{ if eq(parameters.terraformAction, 'Plan') }}:
      - stage: Plan
        displayName: 'Terraform Plan'
        jobs:
          - job: TerraformPlan
            displayName: 'Terraform Plan'
            steps:
              - checkout: self
              - template: terraform/terraform-dev.yaml@templates
                parameters:
                  terraformAction: plan
                  serviceConnectionName: $(serviceConnectionName)
                  backendResourceGroupName: $(backendResourceGroupName)
                  backendStorageAccountName: $(backendStorageAccountName)
                  backendContainerName: $(backendContainerName)
                  backendKey: terraform.tfstate
                  envTfvars: $(tfvars)
                  globalTfvars: $(globalTfvars)
                  additionalCommandOptions: '${{ parameters.additionalTfVars }} -var=enable_eventgrid_subscription=false'

  # Terraform Apply
  - ${{ if eq(parameters.terraformAction, 'Apply') }}:
      - stage: ApplyBase
        displayName: 'Terraform Apply - Base Infrastructure'
        jobs:
          - job: TerraformApplyBase
            displayName: 'Terraform Apply - Base'
            steps:
              - checkout: self
              - template: terraform/terraform-dev.yaml@templates
                parameters:
                  terraformAction: apply
                  serviceConnectionName: $(serviceConnectionName)
                  backendResourceGroupName: $(backendResourceGroupName)
                  backendStorageAccountName: $(backendStorageAccountName)
                  backendContainerName: $(backendContainerName)
                  backendKey: terraform.tfstate
                  envTfvars: $(tfvars)
                  globalTfvars: $(globalTfvars)
                  additionalCommandOptions: '${{ parameters.additionalTfVars }} -var=enable_eventgrid_subscription=false'

      - stage: FunctionDeploy
        displayName: 'Deploy Function App Code'
        dependsOn: ApplyBase
        condition: succeeded()
        jobs:
          - job: FunctionDeploy
            displayName: 'Deploy Function App Code'
            steps:
              - checkout: self

              - task: NodeTool@0
                displayName: 'Select Node Version'
                inputs:
                  versionSpec: '22.x'

              - script: |
                  set -euo pipefail
                  cd functions/src
                  npm ci
                  npm run build --if-present
                  npm prune --omit-dev
                displayName: 'Build Functions'

              - task: ArchiveFiles@2
                displayName: 'Zip Functions'
                inputs:
                  rootFolderOrFile: 'functions/src'
                  includeRootFolder: false
                  archiveType: zip
                  archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
                  replaceExistingArchive: true

              - task: AzureCLI@2
                displayName: 'Deploy Functions'
                inputs:
                  azureSubscription: $(serviceConnectionName)
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    set -euo pipefail
                    az functionapp deployment source config-zip \
                      --resource-group "$FUNCTION_RG" \
                      --name "$FUNCTION_APP" \
                      --src "$PACKAGE_PATH"
                env:
                  FUNCTION_RG: $(functionResourceGroupName)
                  FUNCTION_APP: $(functionAppName)
                  PACKAGE_PATH: $(Build.ArtifactStagingDirectory)/functionapp.zip

              - task: AzureCLI@2
                displayName: 'Wait For Function To Exist'
                inputs:
                  azureSubscription: $(serviceConnectionName)
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    set -euo pipefail
                    SUB_ID="$(az account show --query id -o tsv)"
                    RG="$FUNCTION_RG"
                    APP="$FUNCTION_APP"
                    FUNC="$FUNCTION_NAME"

                    for i in {1..60}; do
                      if az rest --method get \
                        --url "https://management.azure.com/subscriptions/${SUB_ID}/resourceGroups/${RG}/providers/Microsoft.Web/sites/${APP}/functions/${FUNC}?api-version=2022-03-01" \
                        >/dev/null 2>&1; then
                        echo "Function ${FUNC} is now visible in ARM"
                        exit 0
                      fi
                      echo "Waiting for function to be visible... (attempt $i/60)"
                      sleep 10
                    done
                    echo "##[error]Function not visible in ARM: ${APP}/functions/${FUNC}"
                    exit 1
                env:
                  FUNCTION_RG: $(functionResourceGroupName)
                  FUNCTION_APP: $(functionAppName)
                  FUNCTION_NAME: $(eventgridFunctionName)

      - stage: ApplyEventGrid
        displayName: 'Terraform Apply - Event Grid'
        dependsOn: FunctionDeploy
        condition: succeeded()
        jobs:
          - job: TerraformApplyEventGrid
            displayName: 'Terraform Apply - Event Grid'
            steps:
              - checkout: self
              - template: terraform/terraform-dev.yaml@templates
                parameters:
                  terraformAction: apply
                  serviceConnectionName: $(serviceConnectionName)
                  backendResourceGroupName: $(backendResourceGroupName)
                  backendStorageAccountName: $(backendStorageAccountName)
                  backendContainerName: $(backendContainerName)
                  backendKey: terraform.tfstate
                  envTfvars: $(tfvars)
                  globalTfvars: $(globalTfvars)
                  additionalCommandOptions: '${{ parameters.additionalTfVars }} -var=enable_eventgrid_subscription=true'

  # Terraform Destroy
  - ${{ if eq(parameters.terraformAction, 'Destroy') }}:
      - stage: Destroy
        displayName: 'Terraform Destroy'
        jobs:
          - job: TerraformDestroy
            displayName: 'Terraform Destroy'
            steps:
              - checkout: self
              - template: terraform/terraform-dev.yaml@templates
                parameters:
                  terraformAction: destroy
                  serviceConnectionName: $(serviceConnectionName)
                  backendResourceGroupName: $(backendResourceGroupName)
                  backendStorageAccountName: $(backendStorageAccountName)
                  backendContainerName: $(backendContainerName)
                  backendKey: terraform.tfstate
                  envTfvars: $(tfvars)
                  globalTfvars: $(globalTfvars)
                  additionalCommandOptions: '${{ parameters.additionalTfVars }} -var=enable_eventgrid_subscription=true'
