trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: liam-goodchild/pipeline-engineering-templates
      endpoint: liam-goodchild
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: terraformAction
    displayName: Terraform Action
    type: string
    default: Plan
    values: [Plan, Apply, Destroy]
  - name: environment
    displayName: Environment
    type: string
    values: [Dev, Prod]
  - name: additionalTfVars
    displayName: Additional Terraform Variables
    type: string
    default: ' '

variables:
  # Container, Service Connection & tfvars
  backendContainerName: infra-template-base
  serviceConnectionName: sh-sc-base
  globalTfvars: infra/vars/globals.tfvars
  tfvars: infra/vars/uks/$(environmentCode).tfvars
  # State Management
  ${{ if eq(parameters.environment, 'Prod') }}:
    backendResourceGroupName: sh-mgmt-prd-uks-tf-rg-01
    backendStorageAccountName: shmgmtprdukstfst01
    environmentCode: prd
  ${{ else }}:
    backendResourceGroupName: sh-mgmt-dev-uks-tf-rg-01
    backendStorageAccountName: shmgmtdevukstfst01
    environmentCode: dev

stages:
  - stage: Terraform
    displayName: 'Terraform ${{ parameters.terraformAction }}'
    jobs:
      - job: TerraformAction
        displayName: 'Terraform ${{ parameters.terraformAction }}'
        steps:
          - checkout: self
          - template: terraform/terraform-dev.yaml@templates
            parameters:
              terraformAction: ${{ lower(parameters.terraformAction) }}
              serviceConnectionName: $(serviceConnectionName)
              backendResourceGroupName: $(backendResourceGroupName)
              backendStorageAccountName: $(backendStorageAccountName)
              backendContainerName: $(backendContainerName)
              backendKey: terraform.tfstate
              envTfvars: $(tfvars)
              globalTfvars: $(globalTfvars)
              additionalCommandOptions: ${{ parameters.additionalTfVars }}
