trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: liam-goodchild/pipeline-engineering-templates
      endpoint: liam-goodchild
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: terraformAction
    displayName: Terraform Action
    type: string
    default: Plan
    values: [Plan, Apply, Destroy]
  - name: environment
    displayName: Environment
    type: string
    default: dev
    values: [dev, prd]
  - name: enableEventGrid
    displayName: Enable Event Grid Subscription
    type: boolean
    default: false
  - name: additionalTfVars
    displayName: Additional Terraform Variables
    type: string
    default: ' '
  - name: envs
    type: object
    default:
      dev:
        backendResourceGroupName: sh-mgmt-dev-uks-tf-rg-01
        backendStorageAccountName: shmgmtdevukstfst01
        tfvars: infra/vars/uks/dev.tfvars
      prd:
        backendResourceGroupName: sh-mgmt-prd-uks-tf-rg-01
        backendStorageAccountName: shmgmtprdukstfst01
        tfvars: infra/vars/uks/prd.tfvars

variables:
  backendContainerName: solution-powertoggle-core
  serviceConnectionName: sh-sc-powertoggle
  globalTfvars: infra/vars/globals.tfvars
  backendResourceGroupName: ${{ parameters.envs[parameters.environment].backendResourceGroupName }}
  backendStorageAccountName: ${{ parameters.envs[parameters.environment].backendStorageAccountName }}
  tfvars: ${{ parameters.envs[parameters.environment].tfvars }}
  ${{ if eq(parameters.enableEventGrid, true) }}:
    eventGridArg: '-var=enable_eventgrid_subscription=true'
  ${{ else }}:
    eventGridArg: '-var=enable_eventgrid_subscription=false'

stages:
  - stage: Terraform
    displayName: 'Terraform ${{ parameters.terraformAction }}'
    jobs:
      - job: TerraformAction
        displayName: 'Terraform ${{ parameters.terraformAction }}'
        steps:
          - checkout: self
          - template: terraform/terraform-dev.yaml@templates
            parameters:
              terraformAction: ${{ lower(parameters.terraformAction) }}
              serviceConnectionName: $(serviceConnectionName)
              backendResourceGroupName: $(backendResourceGroupName)
              backendStorageAccountName: $(backendStorageAccountName)
              backendContainerName: $(backendContainerName)
              backendKey: terraform.tfstate
              envTfvars: $(tfvars)
              globalTfvars: $(globalTfvars)
              additionalCommandOptions: '${{ parameters.additionalTfVars }} $(eventGridArg)'
